theme: jekyll-theme-slate
title: Mayank Bambal
description: Software Engineer Portfolio

# Optional configuration
show_downloads: true
google_analytics: # Add your Google Analytics tracking ID here if needed

# Build settings
markdown: kramdown
baseurl: ""
url: "https://mayankbambal.github.io" 